### ISSUE TITLE
[Please Help] - Add Example for demo ProcedureManager 

### ISSUE THREAD

**Issue by codingwatching** [DonnYep/CosmosFramework#10]
Hi @DonnYep 
I see the ProcedureManager module in the Framework and I think it is the State Base manager for controlling the game state.
Please add an example of how to use it
Thank you so much

**Comment by DonnYep** [comment]
@codingwatching The procedure demo has been submitted, please check the latest submission history.

**Comment by codingwatching** [comment]
Hi @DonnYep It is an awesome example! (as usual)
Thank you so much and have a nice day!
