### ISSUE TITLE
[Bug] - TickTimer PauseTask and UnPauseTask

### ISSUE THREAD

**Issue by codingwatching** [DonnYep/CosmosFramework#11]
Hi @DonnYep 
I am trying using TickTimer feature. When testing Pause and Resume (UnPause), I see the problem that PauseTask removes the task from taskDict but in UnPauseTask, the taskDict is not adding the task again, so the task can not be resumed.
Please check 

```
  public bool PauseTask(int taskId)
        {
            if (!taskDict.TryRemove(taskId, out TickTask task))
                return false;
            task.IsPause = true;
                var remainTime= task.DestTime - GetUTCMilliseconds();
            task.PauseRemainTime = remainTime > 0 ? remainTime : 0;
            return true;
        }
        public bool UnPauseTask(int taskId)
        {
            if (!taskDict.TryRemove(taskId, out TickTask task))
                return false;
            task.IsPause = false;
            task.DestTime = task.PauseRemainTime + GetUTCMilliseconds();
            return true;
        }
```

**Comment by DonnYep** [comment]
Hi @codingwatching 
Thanks for the feedback on the bug, I have fixed and added a tickTimer example.
Thank you so much !

**Comment by codingwatching** [comment]
Hi @DonnYep 
Thank you so much for the quick update Pause and UnPause of TickTimer
I am testing that example and I found that after a pause (for example 10s), the text immediately reaches 10s after
I think just because after the pause function, we still use this to calculate DestTime
```
task.DestTime = task.StartTime + task.IntervalTime * (task.LoopIndex + 1);
```
Please check the example again:
1. Click Run
2. Click Pause and wait for 10s, for example, the text show 5s
3. Click UnPause, the text will show 15s (I think it should be 6s)

**Comment by DonnYep** [comment]
Hi @codingwatching 
Thank you for finding this error, for which I have made a fix. The code has been uploaded. Please give me feedback if you have any questions and I will respond as soon as possible.
Thank you !

**Comment by codingwatching** [comment]
@DonnYep Thank you!
