### ISSUE TITLE
[Question] - Should we add PauseAllTask and UnPauseAll Task into TickTimer

### ISSUE THREAD

**Issue by codingwatching** [DonnYep/CosmosFramework#13]
Hi @DonnYep 
I am using TickTimer to spawn tasks and when the game pause, I need to pause all task too
Should we add 2 functions for that purpose into TickTimer?
```
        public void PauseAllTask()
        {
            foreach (var taskId in taskDict.Keys)
            {
                PauseTask(taskId);
            }
        }

        public void UnPauseAllTask()
        {
            foreach (var taskId in taskDict.Keys)
            {
                UnPauseTask(taskId);
            }
        }

```

Thank you!

**Comment by DonnYep** [comment]
Hi @codingwatching 
If you need to pause all tasks when game pause, I recommend stop calling TickRefresh() to stop all tasks. Of course the method you propose is also possible.

**Comment by codingwatching** [comment]
Hi, @DonnYep
Yes, stop calling TickRefresh is an awesome way to do it!
