### ISSUE TITLE
MVC.RegisterAttributedMVC() 不支持有参构造函数

### ISSUE THREAD

**Issue by tpxxn** [DonnYep/CosmosFramework#14]

**Comment by DonnYep** [comment]
@tpxxn 嗨，你有写的遇到问题代码吗，我看一下。目前计划通过attribute为有参构造传入参数，当然，如果没有与有参构造对应的attribute，会抛出异常。

**Comment by tpxxn** [comment]
就只是尝试了一下RegisterAttributedMVC这个功能，发现不支持，目前没有在使用
