### ISSUE TITLE
[Please Help] - How to build Assets Bundle on Android platform

### ISSUE THREAD

**Issue by codingwatching** [DonnYep/CosmosFramework#15]
Hi @DonnYep 
Please help me with some notes on how to build the game for the android devices that we will use ResourceLoadMode is AssetBundle
(I just can now build and run the game in Resource mode by moving all the prefab to the Resources folder)
Thank you so much!

**Comment by DonnYep** [comment]
If you need to use **AssetBundle** mode ,you need to do the following :

**1. After configuring according to this image, click build assetBundle button.**
![ab](https://user-images.githubusercontent.com/44013616/199255374-7828fb7b-e0fb-44af-b671-9319d1f4bdf9.png)

**2. Set cosmos config as follow.**
![ab1](https://user-images.githubusercontent.com/44013616/199256113-0c08c68b-78b7-4ea9-8201-22352156b4be.png)

After the resource module has been initialized, you can use the **AssetBundle** mode.

**Comment by codingwatching** [comment]
Hi @DonnYep 
Thank you so much!
So AssetBundle is followed by ResourceDateset config? Could you please take some notes on ResourceDataset too
(How to create ResourceDataset and how to create a list of the bundle inside it and the detailed assets in that bundle)
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/85933804/199283994-d93941bc-85e7-4979-b95a-9db6f5dcead4.png">
Thank you!

**Comment by codingwatching** [comment]
And after build AssetBundle, I tried to test in the editor, it shows an error like this:
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/85933804/199275942-2bc21279-21b1-465c-b254-567bada47880.png">

I double check the folder and file manifest is generated
<img width="782" alt="image" src="https://user-images.githubusercontent.com/85933804/199276796-c010649c-a7f6-44f8-bfe7-cc6e1fefecb5.png">

**Comment by DonnYep** [comment]
Hi @codingwatching    
You can watch this video to see how resource editor work, the start time is 2.13 .
url: https://www.bilibili.com/video/BV11P4y1U7vB/?spm_id_from=333.999.0.0&vd_source=72155bd9fe7a235574a00a4585c528fc


I recommend that you create your own Resourcedataset,the one that existed was the one I used for the demo,so it may  cause some error after build android.

**Comment by DonnYep** [comment]
@codingwatching  I'm writing the resource editor documentation and will upload it as soon as I'm done

**Comment by codingwatching** [comment]
@DonnYep Thank you so much for the video of CosmosFramework, nice and polished video!
I now have some basics to create a new Resourcedataset and use it. When switching to android, I still have errors, and I print out the stack trace from OnManifestFailure callback and get the:  **Cannot connect to destination host**
```
[ERROR]-->> ResourceManifest deserialization failed , check your file: **Cannot connect to destination host**
```


I hope with that errorMessage, you can help me more quickly. 
I google for the error and I think maybe we should use AssetBundle.LoadFromFileAsync instead of UnityWebRequest
```
The default behavior is to use AssetBundle.LoadFromFileAsync when the AssetBundle is in local storage and use UnityWebRequest when the AssetBundle path is a URL.

```

Thank you so much! You help me a lot!

**Comment by DonnYep** [comment]
Hi @codingwatching I'm very sorry for the impact, I will fix this error in the next few commits.

**Comment by codingwatching** [comment]
Hi, @DonnYep Thank you so much, and Take It easy! I am happy when trying to understand code! That way I can learn more deeply and faster.

**Comment by DonnYep** [comment]
Hi @codingwatching  I have tested it on Android devices and this error has been fixed and submitted, thank you for your feedback : ) .

**Comment by codingwatching** [comment]
@DonnYep Thank you so much! I just checkout the project and success build and run on Android too
So, on the editor, we can not test AssetBundle mode? (I know we should use AssetDatabase mode to fast develop)
If yes then lucky for me to find out this bug, because I just tried using AssetBundle on Editor but It not works (And then I build on an android device to test too)
<img width="302" alt="image" src="https://user-images.githubusercontent.com/85933804/199642322-3b984da2-9346-474f-9af3-6ec3477e9cda.png">

**Comment by DonnYep** [comment]
Hi @codingwatching 
     You can use AssetBundle mode in editor mode, but the limitation is that the build AssetBundle needs to correspond to the platform. If you want to use AssetBundle in editor, you need to change the build target to Standalone Windows when you build AssetBundle. In addition, all loading modes are available in the editor environment.
    The use of AssetDatabase mode is to speed up the development progress in the editor environment, and it is necessary to switch to ab mode when building the app, which is the current mainstream development strategy.

**Comment by DonnYep** [comment]
Hi @codingwatching 
I recommend you to create your own ResourceDataset instead of using the one that exists in my case. The ResourceDataset that existed will have some problems after building the app, because there are a lot of settings to deal with. If you create your own ResourceDataset, then you only need to deal with your own resources. I will upload a case to the demo repo, you can check out the 23 entity demo.

**Comment by codingwatching** [comment]
@DonnYep Thank you so much! Have a nice day!

**Comment by codingwatching** [comment]
@DonnYep A dedicated ResourceDataset file for demo 23_entity builds on android would be awesome!
Thank you for the support!
