### ISSUE TITLE
How to handle Entity Life Cycle

### ISSUE THREAD

**Issue by codingwatching** [DonnYep/CosmosFramework#16]
Hi @DonnYep 
I am reading the Entity Example and applying it to my game.
I want to reset some logic data (from table config) each time Entity is shown again, so I need some exclusive Functions like this:

- OnInit (Can replace by Awake)
- OnShow
- OnHide

After reading the code, I think we can implement that functions in EntiyHelper and EntityGroupHelper classes but should we provide it in Entity Class?
Thank you so much!

**Comment by DonnYep** [comment]
Hi @codingwatching 
I'm working on this part and will update it in a later commit.

**Comment by codingwatching** [comment]
@DonnYep Thank you so much!

**Comment by DonnYep** [comment]
Hi @codingwatching  I have updated the entity example, please check the commit.

**Comment by codingwatching** [comment]
Thank you so much @DonnYep ! It is polished and easy to understand now!
