### ISSUE TITLE
DefaultDownloadRequester.cs EnumGetFileSize函数if逻辑写反了

### ISSUE THREAD

**Issue by angking0802wu** [DonnYep/CosmosFramework#21]
IEnumerator EnumGetFileSize(string uri, Action<long> callback)
        {
            using (UnityWebRequest request = UnityWebRequest.Head(uri))
            {
                yield return request.SendWebRequest();
                string size = request.GetResponseHeader("Content-Length");

                if (request.result != UnityWebRequest.Result.ConnectionError && request.result != UnityWebRequest.Result.ProtocolError)
                    callback?.Invoke(-1);
                else
                    callback?.Invoke(Convert.ToInt64(size));
            }
        }

**Comment by DonnYep** [comment]
感谢发现，此代段代码已修复。

**Comment by DonnYep** [comment]
感谢发现，此段代码已修复。
