### ISSUE TITLE
20_AOI SquareGrid.cs数组越界

### ISSUE THREAD

**Issue by angking0802wu** [DonnYep/CosmosFramework#22]
public Square[] GetNearbySquares(float posX, float posY, int level = 0)
        {
            if (!IsOverlapping(posX, posY))
                return new Square[0];
 ！！！重复           if (!IsOverlapping(posX, posY))
 ！！！重复               return new Square[0];
            
！！！            var row = (int)((posX - OffsetX) / CellSideLength);
！！！            var col = (int)((posY - OffsetY) / CellSideLength);
            
            level = level >= 0 ? level : 0;
            if (level == 0)
                return new Square[] { square2d[col, row] };
            if (level == CellSection)
                return square1d;
            int sideCellCount = level * 2 + 1;
            int squareCount = sideCellCount * sideCellCount;
            Square[] neabySquares = new Square[squareCount + 1];
            int idx = 0;
            for (int x = -level; x <= level; x++)
            {
                for (int y = -level; y <= level; y++)
                {
                    int idxX = col + x;
                    int idxY = row + y;
                    if (idxX < CellSection && idxX >= 0 && idxY < CellSection && idxY >= 0)
                    {
                        neabySquares[idx] = square2d[idxX, idxY];
                        idx++;
                    }
                }
            }
            var dstSquares = new Square[idx];

！！！越界           dstSquares[0] = square2d[col , row];

            Array.Copy(neabySquares, 0, dstSquares, 0, idx);
            return dstSquares;
        }

**Comment by DonnYep** [comment]
非常感谢发现这个bug，数据结构SquareGrid现修复已提交。
