### ISSUE TITLE
Client.cs中ReceiveThreadFunction函数中少了Finally

### ISSUE THREAD

**Issue by angking0802wu** [DonnYep/CosmosFramework#23]
！！！下面语句应该放finally中

            // add 'Disconnected' event to receive pipe so that the caller
            // knows that the Connect failed. otherwise they will never know
            state.receivePipe.Enqueue(0, EventType.Disconnected, default);
            
            // sendthread might be waiting on ManualResetEvent,
            // so let's make sure to end it if the connection
            // closed.
            // otherwise the send thread would only end if it's
            // actually sending data while the connection is
            // closed.
            sendThread?.Interrupt();

            // Connect might have failed. thread might have been closed.
            // let's reset connecting state no matter what.
            state.Connecting = false;

            // if we got here then we are done. ReceiveLoop cleans up already,
            // but we may never get there if connect fails. so let's clean up
            // here too.
            state.client?.Close();
        }

**Comment by DonnYep** [comment]
如果这段代码在执行的时候会引发异常，那确实应该放在finally语句中，以令try重写捕获。不过这段只是做了释放终结处理，并不会引发异常，没有必要放在finally语句块中。
另外这是第三方库，git地址 : https://github.com/vis2k/Telepathy 
我个人倾向Telepathy作者的处理方式。

**Comment by angking0802wu** [comment]
明白了 谢谢
