### ISSUE TITLE
请教一下WaitForMainThread的用法

### ISSUE THREAD

**Issue by zaenzhang** [DonnYep/CosmosFramework#25]
我写了如下的测试代码，发现"Down"的Log顺序在"AwaitableTest >>> After IEnumerator EnumWait"之后，
![image](https://user-images.githubusercontent.com/23573175/207845912-8b32609a-cdb9-455a-9e8c-10af23142b4c.png)

```csharp
 IEnumerator EnumWait()
    {
        yield return new WaitForSeconds(3);
        Task task = new Task((() =>
        {
            Thread.Sleep(2000);
            Debug.Log("Down");
        }));
        task.Start();
        yield return task;
        Debug.Log("AwaitableTest >>> After IEnumerator EnumWait");
    }
```
但是当我将`yield return task`修改成`yield return task.AsCoroutine();`结果会变成
![image](https://user-images.githubusercontent.com/23573175/207846743-b0ef5778-2349-4f14-8964-0a2d6fb2ea3e.png)

所以想请教一下WaitForMainThread的用法

**Comment by DonnYep** [comment]
11_AwaitableTest展示的是async/await语法对Unity协程的支持。Task本身并不是迭代器，且Unity协程没有对Task做yield return支持，因而不能直接yield return Task，而是需要转换成协程(task.AsCoroutine)才可被 yield return。

**Comment by zaenzhang** [comment]
非常感谢
