### ISSUE TITLE
框架Resource模块是否能够同步加载资源?

### ISSUE THREAD

**Issue by foreversos** [DonnYep/CosmosFramework#26]
目前看来所有加载资源的方法都是异步的,不知道有没同步的方式
由于本人不熟习异步思路开发,感觉困难重重
主要在与异步的污染性,一条代码是异步导致所有上层都要改为异步.
这样来,代码凡是和加载资源有关的(创建预制体这种很频繁的操作),都需要改为异步
在资源加载逻辑上下游也要变为异步

**Comment by DonnYep** [comment]
v1.3版本资源加载底层均为异步，但也针对同步加载做了async/await扩展。async/await同步加载可在v1.3版本中PRX_Inventory.cs 的17行进行查看。若async/await加载无法满足你的需求，请移步至[QuarkAsset](https://github.com/DonnYep/QuarkAsset)。QuarkAsset支持同步、异步，以及多地址加载。

**Comment by DonnYep** [comment]
框架Resource模块在v1.3版本不会考虑支持同步加载，但是会在之后的版本中支持。

**Comment by foreversos** [comment]
> v1.3版本资源加载底层均为异步，但也针对同步加载做了async/await扩展。async/await同步加载可在v1.3版本中PRX_Inventory.cs 的17行进行查看。若async/await加载无法满足你的需求，请移步至[QuarkAsset](https://github.com/DonnYep/QuarkAsset)。QuarkAsset支持同步、异步，以及多地址加载。

好的,我先看看示例里面的
