### ISSUE TITLE
请教输入模块怎么新增和映射新的按钮

### ISSUE THREAD

**Issue by foreversos** [DonnYep/CosmosFramework#27]
目前InputButtonType有部分按钮.但是缺乏我想要的
比如我要增加一个按空格,应该怎么添加
如果SPACE是个字符串,怎么与实际的按钮绑定?

**Comment by DonnYep** [comment]
拉取最新的内容，并搜索26_CustomInput。此部分包含自定义输入映射案例。

**Comment by foreversos** [comment]
了解~
