### ISSUE TITLE
建议:资源加载失败的时候打印一个警告

### ISSUE THREAD

**Issue by foreversos** [DonnYep/CosmosFramework#28]
想起之前容易出错的一点就是场景管理器切换场景的时候,调用了方法但是没任何反应,场景也没切换成功
后来才发现是SCENE的资源路径错误了,但是系统没提示,排查起来费劲

**Comment by DonnYep** [comment]
![cf_print_res_log](https://github.com/DonnYep/CosmosFramework/assets/44013616/c2527d01-1876-4956-a013-832299547fea)
拉取v1.3最新内容后，会有这么一个选项，勾选后会打印资源加载失败的日志。

**Comment by foreversos** [comment]
好,我目前使用的是UPM方式,所以使用的时候不会改动框架代码
不清楚UPM是否是和GIT同步的,所以暂时记录,等未来UPM更新

**Comment by DonnYep** [comment]
![image](https://github.com/DonnYep/CosmosFramework/assets/44013616/842cc23c-3be4-4d67-a671-83d694c44b8a)

能告诉我你使用的其中的哪种方式导入的吗？

**Comment by foreversos** [comment]
我是使用的第三种,谢谢~

**Comment by foreversos** [comment]
已更新到1.3.2已经有了,看来是自动同步的,不需要你手动去同步
