### ISSUE TITLE
框架不错，希望能持续更新

### ISSUE THREAD

**Issue by 89t-yiming** [DonnYep/CosmosFramework#4]
感谢 开源这个框架。

最担心开发者因为其他事情导致这种框架类项目中途停滞，半途而废，希望这个项目不要出现这种情况。

**Comment by DonnYep** [comment]
非常感谢对本框架的支持，能有这样的鼓励对我来说是更新维护的动力。我知道我的框架本身并不完美，我也在持续维护并更新功能，所以有遇到问题，还请诸君多提issue，我会尽我所能解决。

本框架会长期维护。技术路漫漫，望与诸君共勉。
