### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by codingwatching** [DonnYep/CosmosFramework#5]
Hi @DonnYep 
Thank you so much for awesome Framework, The examples list are very easy to run
When I try to run 08_ObjectPool, I see the null error here, Please check

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/85933804/195231063-db2c5539-3bcf-4c7d-ad8e-2341ff798122.png">

```
NullReferenceException: Object reference not set to an instance of an object
Cosmos.Test.MyObjectSpawner+<Start>d__13.MoveNext () (at Assets/Examples/ExampleScripts/08_ObjectPool/MyObjectSpawner.cs:36)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext:ExecuteTasks() (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)

```
Thank you so much!

**Comment by DonnYep** [comment]
Hi @codingwatching 
Thank you very much for your attention to my framework, this issue will be fixed immediately. If you find any other issues, please give me feedback and I will respond immediately. 
Thank you very much.

**Comment by codingwatching** [comment]
Hi @DonnYep 
Thank you! Have a nice day!

**Comment by codingwatching** [comment]
<img width="994" alt="image" src="https://user-images.githubusercontent.com/85933804/195481126-5a7b99ea-3c4e-459b-b066-2c43128ea1d2.png">

Thank you for the quick update, it works like a charm now!

**Comment by DonnYep** [comment]
Hi @codingwatching 
Glad to help you and look forward to more feedback from you!
Thank you!
