### ISSUE TITLE
Add Example for demo Entity and EntityManager please

### ISSUE THREAD

**Issue by codingwatching** [DonnYep/CosmosFramework#6]
Hi @DonnYep 
I am learning the framework, and the Examples list is awesome so far. For now, I am learning Entity and EntityManager but I can not search for any example code in [CosmosFramework](https://github.com/DonnYep/CosmosFramework)

A simple game with players, enemies, and bullets with reuse entities, and exchange events, would be great!
Thank you!

**Comment by DonnYep** [comment]
Hi @codingwatching 
Thank you very much for your approval of my framework, entity module I will add new cases based on your suggestions. Also please contact me if you have any questions, it is a great encouragement for me that you use my framework!
Thank you!

**Comment by codingwatching** [comment]
@DonnYep I am waiting for this!  Thank you so much for the added examples so far
Have a nice weekend!

**Comment by DonnYep** [comment]
@codingwatching The example of entity module is in the development, I will finish and submit it as soon as possible.

**Comment by DonnYep** [comment]
Hi @codingwatching  
I have uploaded a simple entity demo. if you want to learn how to write a full game by using cosmosframework, please follow the cosmosframework-demo repo and I will develop a more fully functional rpg game in my spare time in the future : ) .

**Comment by DonnYep** [comment]
The name of entity demo is "23_EntityLauncher".

**Comment by codingwatching** [comment]
Hi @DonnYep It is a big gift for me! Let start a week with learning Entity Example!
Thank you so much!
