### ISSUE TITLE
TickTimer Error in some case?

### ISSUE THREAD

**Issue by codingwatching** [DonnYep/CosmosFramework#7]
@DonnYep 
I am trying the ObjectPool example and when I change the timer config to:
```
            //注意，这里是毫秒单位；
            tickTimer.AddTask(100, OnSpawnTime, null, int.MaxValue);
            //此写法的实际意义为，生成的单位存活时间为15秒；
            //await new WaitForSeconds(15f);
            tickTimer.AddTask(10, 1500, OnDespawnTime, null, int.MaxValue);

```

Then it errors :

```
NullReferenceException: Object reference not set to an instance of an object
Cosmos.TickTimer.TickRefresh () (at Assets/CosmosFramework/Runtime/Base/Timer/TickTimer.cs:192)
Cosmos.Test.MyObjectSpawner.Update () (at Assets/Examples/ExampleScripts/08_ObjectPool/MyObjectSpawner.cs:52)
```

Maybe we need to check some conditions to avoid this situation .. ?

Thank you so much!

**Comment by DonnYep** [comment]
Hi @codingwatching 
Thank you for your question, there is no error in TickTimer itself. The reason for the error is that you set the despawn speed faster than the spawn speed, and there is no element in the cache queue,  which causes the cache queue dequeue operation to fail and cause an exception.
You can use the following code instead of OnDespawnTime method:
```csharp
void OnDespawnTime(int idx)
{
    {
        if (cubeCache.Count > 0)
        {
            var go = cubeCache.Dequeue();
            cubePool.Despawn(go);
        }
    }
    {
        if (sphereCache.Count > 0)
        {
            var go = sphereCache.Dequeue();
            spherePool.Despawn(go);
        }
    }
    {
        if (capsuleCache.Count > 0)
        {
            var go = capsuleCache.Dequeue();
            capsulePool.Despawn(go);
        }
    }
}

```
Thank you so much!

**Comment by codingwatching** [comment]
@DonnYep Thank you, so the error handle should be written in-game logic like above, not the framework itself!

**Comment by DonnYep** [comment]
@codingwatching Glad to help you, have a nice day : ) !
