### ISSUE TITLE
[Question] - What is difference between AssetBundle and AssetDatabase mode in ResourceLoadMode

### ISSUE THREAD

**Issue by codingwatching** [DonnYep/CosmosFramework#8]
Hi @DonnYep 
I am learning ResourceLoadMode: 
+ Resource
+AssetBundle
+AssetDatabase

Could you please write some notes on what is AssetBundle  mode, Resource mode, and what is AssetDatabase mode
When to use each mode, if we build for mobile devices, what mode should we use?
Is AssetDatabase similar to the addressable assets of Unity?
Thank you so much!

**Comment by DonnYep** [comment]
Hi @codingwatching 

I recommend using AssetDatabase mode in unity editor to speed up your development process. When you need to build the app, it is recommended to change to AssetBundle mode.Resource mode is a wrapper for Unity Resources.

You can check the following links: 
- Resources : https://docs.unity3d.com/ScriptReference/Resources.html
- AssetDatabase : http://www.vfkjsd.cn/unity3d/Manual/AssetDatabase.html
- AssetBundle : https://docs.unity3d.com/Manual/AssetBundlesIntro.html

AssetDatabase is not the same as addressable. Addressable is a complete resource management solution, the AssetDatabase mode I provide is just the underlying Unity AssetDatabase loading method in the unity editor.

I will update the readme file in more detail to explain the usage of the resource module.

Hope it can help you : ) !

**Comment by codingwatching** [comment]
Hi @DonnYep I got it! Thank you so much for the detail explanation. I really appreciate your support!

**Comment by DonnYep** [comment]
@codingwatching I'm glad this helped you : )
