### ISSUE TITLE
Small error in AssetDatabaseTab when using with Unity 2021.3

### ISSUE THREAD

**Issue by codingwatching** [DonnYep/CosmosFramework#9]
Hi @DonnYep 
In AssetDatabaseTab.cs line 330, I think we have small error here:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/85933804/196139593-b833a9e4-2059-4d97-a830-97c5e9bca6b2.png">

Please check
Thank you!

**Comment by DonnYep** [comment]
@codingwatching Thank you for your feedback, this error I have fixed and uploaded.
